# Generated by Django 4.1.6 on 2023-02-10 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctionlisting_comment_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
